[services.backend]
path = "Backend"
start = "npm install && npm start"
language = "node"

[services.frontend]
path = "frontend"
start = "npm install && npm run build && npx serve -s build"
language = "node"
